spring:   
   rabbitmq:
      host: localhost 
      port: 5672
      username: guest
      password: guest
      listener:
         simple:
           missing-queues-fatal: false
           auto-startup: true
   mongodb:
      uri: mongodb://127.0.0.1:27017/userdb
   cloud:
      bus:
         enabled: true
#logging:
#   level:
#      org:
#         mongodb:
#            driver: DEBUG
management:
   endpoints:
      web:
         exposure: 
            include: "*"
   tracing:
      sampling:
         probability: 1.0
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
         defaultZone: http://localhost:8761/eureka
logging:
   file:
      name: ../logs/${spring.application.name}.log
   logback:
      rollingpolicy:
         max-file-size: 5mb
         max-history: 7
server:
   port: 8082
