spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/configdb
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      
      
   cloud:
      config:   
         server:
            jdbc:
               sql: "SELECT PROP_KEY,PROP_VALUE from configdb.properties where APPLICATION = ? and  PROFILE = ? and LABEL = ?"
               default-label: main
                  
                  