services:
   mysql:
      container_name: mysql_container
      image: mysql
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: ecomm
         MYSQL_USER: ecomm
         MYSQL_PASSWORD: root
      volumes:
         - mysql_data:/var/lib/mysql
      ports:
         - 3307:3306
      networks:
         - mysql
      restart: unless-stopped
   phpmyadmin:
      container_name: phpmyadmin_container
      image: phpmyadmin/phpmyadmin
      environment:
         PMA_HOST: mysql
         PMA_PORT: 3306
         MYSQL_ROOT_PASSWORD: root
      ports:
         - "8484:80"
      networks:
         - mysql
      restart: unless-stopped
   postgres:
      container_name: postgresqldb
      image: postgres:14
      environment:
         POSTGRES_USER: root
         POSTGRES_PASSWORD: root
         PGDATA : /data/postgres
         TZ: Asia/Kolkata   
      volumes:
         - postgres:/data/postgres
      ports:
         - "5432:5432"
      networks:
         - postgres
      restart: unless-stopped
      
   pgadmin:
      container_name: PGADMIN
      image: dpage/pgadmin4
      environment:
         PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org} 
         PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin} 
         PGADMIN_CONFIG_SERVER_MODE: False
         TZ: Asia/Kolkata    
      volumes:
         - pgadmin:/var/lib/pgadmin
      ports:
         - "5050:80"
      networks:
         - postgres
      restart: unless-stopped
   rabbitmq:
      image: "rabbitmq:3-management"
      ports:
         - "5672:5672"
         - "15672:15672"
      networks:
         - postgres
networks:
   postgres:
      driver: bridge
   mysql:
      driver: bridge
      
volumes:
   postgres:
   pgadmin:
   mysql_data:
         